global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:2002']

	  
	  
	  
	  
	  #http://localhost:3000/
	  #http://localhost:2002/actuator/prometheus
	  #http://localhost:9090